# permissions for end users to view postgresqlgrants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlgrant-viewer-role
rules:
- apiGroups:
  - database-account-operator.my.domain
  resources:
  - postgresqlgrants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database-account-operator.my.domain
  resources:
  - postgresqlgrants/status
  verbs:
  - get
