# permissions for end users to edit postgresqlgrants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlgrant-editor-role
rules:
- apiGroups:
  - database-account-operator.my.domain
  resources:
  - postgresqlgrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database-account-operator.my.domain
  resources:
  - postgresqlgrants/status
  verbs:
  - get
